- packages/service/src/Demo/pages/DemoPage.tsx
- packages/service/src/Demo/pages/MarqueeDemoPage.tsx
- packages/service/src/Main/pages/MainPage.tsx
- packages/service/src/common/components/Marquee/Marquee.css.ts
- packages/service/src/common/components/Marquee/Marquee.tsx
- packages/service/src/common/components/Marquee/index.tsx
- packages/service/src/common/utils/formatter.ts
- packages/service/src/constants/routes.ts
- packages/service/src/index.css
- packages/service/src/router.tsx
https://watermelon-clap.atlassian.net/browse/CLAP-58
Marquee 컴포넌트 구현
-> 이후 기대평 카드 컴포넌트를 구현 후 해당 Marquee를 통해 움직이는 모션을 나타낼 수 있음
@thgee 
https://github.com/user-attachments/assets/67fc2fd8-78bd-43c0-b905-3f4c2d7cc6f0
> feat(CLAP-58): Marquee 컴포넌트 만들기

- packages/service/src/common/components/Marquee/Marquee.css.ts
- packages/service/src/common/components/Marquee/Marquee.tsx
- packages/service/src/components/main/Expectation/Expectations.tsx
- packages/service/src/components/main/Expectation/index.ts
- packages/service/src/components/main/Expectation/style.ts
- packages/service/src/components/main/index.ts
- packages/service/src/pages/Main/Main.tsx
- https://watermelon-clap.atlassian.net/browse/CLAP-82
- 기대평 카드 구현하고 Marquee 사용하여 메인페이지에 노출
- Marquee 로직 수정 필요함
- @DaeWon9
> feat(CLAP-82): 메인페이지 기대평 구현

- packages/service/src/common/responsive/responsive.ts
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-126?atlOrigin=eyJpIjoiMTQ5MDc2Y2NiOTIyNDdhOGJjYjlhZjk5NDczN2VhNjkiLCJwIjoiaiJ9)
<br/>
- 반응형 웹을 구현하기로 결정하면서 css 내부에 아래와 같은 보일러플레이트 코드가 발생할 것으로 예상하였습니다.
```
@media screen and (max-width: "412px") {
}
```
- 이를 함수로 만들어두면 코드가 간단해질 것 같아 함수화 하였습니다.  
<br/>
- 모바일 뷰의 너비는 Galaxy S20 Ultra 기기의 width인 "412px"을 기준점으로 채택했습니다.
- 미디어쿼리 함수는 아래 예시와 같이 사용할 수 있습니다.
```
예시)
export const bannerContent = css`
font-size : 28px;
${mobile(css`
font-size: 12px;
`)} 
`;
```
<br/>
- @DaeWon9
> feat(CLAP-126): 모바일 반응형 미디어쿼리 함수화

- packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.css.ts
- packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.tsx
- packages/service/src/components/nQuizEvent/NQuizTitle/index.ts
- packages/service/src/components/nQuizEvent/index.ts
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-85?atlOrigin=eyJpIjoiNWEyOGQ1MWJiYTgxNDI5ZGE0MjM4Y2I5NGQxZDZmM2MiLCJwIjoiaiJ9)
<br/>
이벤트소개 헤더 구현
NQuizEvent 페이지 상단부에 해당 이벤트의 정보를 보여주는 컴포넌트의 필요
<br/>
@thgee
> feat(CLAP-85): 이벤트소개 헤더 구현

- packages/service/src/common/components/ModalContainer/AlertModal/AlertModal.css.ts
- packages/service/src/common/components/ModalContainer/AlertModal/AlertModal.tsx
- packages/service/src/common/components/ModalContainer/AlertModal/index.ts
- packages/service/src/common/components/ModalContainer/GoolgleLoginModal/GoogleLoginModal.tsx
- packages/service/src/common/components/ModalContainer/ModalContainer.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-128)
<br/>
공통으로 사용 될 AlertModal 구현
서비스 전반적으로 AlertModal이 필요했고
이에, Title, Content를 props로 넘겨받아 보여주는 Modal의 필요성 대두
```
export interface AlertModalProps extends DefaultModalProps {
title: ReactNode;
content: ReactNode;
}
export const AlertModal = ({
isOpen,
onRequestClose,
title,
content,
}: AlertModalProps) => {
useScrollStop(isOpen);
return (
<Modal
shouldCloseOnEsc
isOpen={isOpen}
onRequestClose={onRequestClose}
style={alertModalStyles}
ariaHideApp={false}
>
<div css={alertModalBodyStyles}>
<h2>{title}</h2>
<div>{content}</div>
<Button variant={ButtonVariant.SHORT} onClick={onRequestClose}>
확인
</Button>
</div>
</Modal>
);
};
```
```
import { useModal } from "@service/common/hooks/useModal";
...
const { openModal } = …
```
> feat(CLAP-128): 공통 모달 만들기

- packages/service/src/common/hooks/useElementViewportPosition.ts
- packages/service/src/components/newCar/NewCarInfo/NewCarInfo.tsx
- [연관된 이슈 링크](https://github.com/softeerbootcamp4th/Team5-WatermelonClap-FE/pull/56#discussion_r1706302783)
<br/>
- 피드백 내용 반영
- NewCarInfo 내부의 useElementViewportPosition 을 hooks 폴더로 분리
- @DaeWon9
> chore: NewCarInfo 내부의 useElementViewportPosition 을 hooks 폴더로 분리

- packages/service/public/images/common/bg-circle-blue.svg
- packages/service/public/images/common/bg-circle-green.svg
- packages/service/src/components/newCar/NewCarInfo/NewCarInfo.css.ts
- packages/service/src/components/newCar/NewCarInfo/NewCarInfo.tsx
- 신차소개 페이지 배경에 원 이미지가 레이어 앞쪽에 돌출되던 이슈 해결
- 코드 순서를 교체하여 해결함
- 이미지 위치도 적절히 수정함
<br/>
- @DaeWon9
> hotfix: 신차소개 페이지 배경에 원 이미지가 레이어 앞쪽에 돌출되던 이슈 해결

- packages/service/src/common/components/Button/Button.tsx
- packages/service/src/common/components/Button/index.ts
- packages/service/src/common/components/Footer/Footer.css.ts
- packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
- packages/service/src/common/components/ModalContainer/AlertModal/AlertModal.css.ts
- packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.css.ts
- packages/service/src/constants/routes.ts
- packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
- packages/service/src/pages/PartsPick/PartsPick.tsx
- packages/service/src/router.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-131)
<br/>
- Footer가 삐져나오는 현상 수정
- 모바일 뷰에서 alertModal 패딩수정
- 선착순 퀴즈 페이지 모바일 뷰 수정
<br/>
@thgee
> hotfix: 모바일 뷰 깨짐 현상 수정

- packages/service/src/components/newCar/NewCarInfo/NewCarInfo.css.ts
- packages/service/src/pages/NQuizEvent/NQuizEvent.css.ts
- 신차소개 페이지 모바일뷰에서 infoImg 가 상단부로 올라갈 때, GNB와 z-index가 같아 GNB위로 올라오는 이슈 수정
- NQuiz 이벤트 페이지에서 min-width가 412로 표기되어있어 해당 사이즈보다 작은 뷰에서 여백이 보이는 이슈 수정
- 신차소개 페이지  infoImg 의 z-idex 수정 999 -> 3
- NQuizEvent.css.ts 내부의 backgroundStyle - mobile 내부의 min-width = 0px 으로 변경
<br/>
@thgee
> hotfix: 모바일 뷰 오류 수정

- packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
- packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.css.ts
- packages/service/src/pages/NQuizEvent/NQuizEvent.css.ts
- packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-132?atlOrigin=eyJpIjoiMzk1NTYxODk1NzA2NDZkYmJkMDI2MDA1YjM0MzE3ZDUiLCJwIjoiaiJ9)
<br/>
모바일뷰에서 Reward 컴포넌트가 잘 안보이는 이슈
<br/>
@thgee
> chore(CLAP-132): 퀴즈페이지 모바일 뷰 수정

- packages/core/src/types/orderEvent/index.ts
- packages/service/src/apis/orderEvent/apiPostOrderEventApply.ts
- packages/service/src/apis/orderEvent/type.ts
- packages/service/src/common/components/ModalContainer/content/modalContent.tsx
- packages/service/src/common/utils/formatter.ts
- packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/NQuizInput.tsx
- packages/service/src/constants/routes.ts
- packages/service/src/pages/NQuizEventWinnerApply/NQuizEventWinnerApply.css.ts
- packages/service/src/pages/NQuizEventWinnerApply/NQuizEventWinnerApply.tsx
- packages/service/src/pages/NQuizEventWinnerApply/index.ts
- packages/service/src/pages/index.ts
- packages/service/src/router.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-67?atlOrigin=eyJpIjoiMmY2NTMyNDdhNmUyNDU1YWExMWRiYzE0ZGRmMjdkNzgiLCJwIjoiaiJ9)
<br/>
선착순 이벤트 당첨 유저 정보 입력페이지 구현
- 선착순 이벤트에 당첨이되면 기존에는 모달이 노출 -> 페이지 이동으로 전환
- 입력폼 구현 
- apI 연동
<br/>
@thgee
> feat(CLAP-67): 당첨자 정보 입력 폼 만들기

- packages/service/src/Demo/pages/ButtonDemoPage.tsx
- packages/service/src/apis/expectation/apiPostExpectation.ts
- packages/service/src/apis/link/apiGetMyShareLink.ts
- packages/service/src/apis/lottery/apiGetLotteryStatus.ts
- packages/service/src/common/components/ClipBoardButton/ClipBoardButton.tsx
- packages/service/src/components/main/EventPeriod/Timer/Timer.css.ts
- packages/service/src/constants/routes.ts
- packages/service/src/index.tsx
- packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.css.ts
- packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.tsx
- packages/service/src/pages/LotteryApplyFinish/index.ts
- packages/service/src/pages/PartsPick/PartsPick.tsx
- packages/service/src/router.tsx
- [연관된 이슈 링크](이슈 링크를 이곳에 넣어주세요.)
<br/>
- 파츠뽑기 후 공유링크, 기대평 작성 등의 작업을 수행할 응모완료 페이지 구현
- 기대평 제출 후 제출버튼을 비활성화 하였습니다.
- 이미 응모했던 사람이 페이지에 접속 시 기대평 입력란이 보이지 않게 하였습니다.
<br/>
- @DaeWon9
> Feat(CLAP-141): 응모 완료 페이지

- packages/core/src/hooks/useAuth.ts
- packages/service/src/components/share/PartsTab/PartsWrap.css.ts
- packages/service/src/pages/PartsCollection/PartsCollection.tsx
- 엑세스토큰 만료, 혹은 로그인하지 않았을 경우의 예외처리를 위해 `useAuth`훅에 `handleTokenError` 함수를 추가하였습니다.
- `useAuth` 내부에서 함수들을 사용할 수 있도록 return 구조를 변경하였습니다.
- 공유링크페이지의 파츠 레이아웃을 `between -> center` 로 수정하였습니다.
<br/>
- @DaeWon9
> chore: 공유링크페이지 디자인수정, useAuth 구조 변경, handleTokenError 함수 추가

- packages/service/src/apis/lottery/apiGetLotteryStatus.ts
- packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
- packages/service/src/constants/routes.ts
- packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.css.ts
- packages/service/src/pages/LotteryApplyInfo/LotteryApplyInfo.css.ts
- packages/service/src/pages/LotteryApplyInfo/LotteryApplyInfo.tsx
- packages/service/src/pages/LotteryApplyInfo/index.ts
- packages/service/src/router.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-142)
<br/>
- 유저 본인이 이벤트에 응모했는지, 응모했다면 공유링크와 남은 뽑기 횟수를 확인할 수 있는 `응모 내역 확인 페이지` 구현
<br/>
- @DaeWon9
> feat(CLAP-142): 응모 내역 확인 페이지

- packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
- packages/service/src/components/nQuizEvent/NQuizSection/NQuizAlternativeBody/NQuizAlternativeBody.css.ts
- packages/service/src/components/nQuizEvent/NQuizSection/NQuizAlternativeBody/NQuizAlternativeBody.tsx
- packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/NQuizInput.tsx
- packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.css.ts
- packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.tsx
- packages/service/src/constants/quizContents.ts
- packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-153?atlOrigin=eyJpIjoiNTkyYWZkZDZjNDQzNDI1OWJiNzA5NGMwZDI5YTg2Y2MiLCJwIjoiaiJ9)
<br/>
퀴즈의 Status별 예외처리를 추가했습니다.
- 퀴즈의 상태는  "UPCOMING" | "OPEN" | "CLOSED" | "END" 가 존재하고 상태별로 퀴즈섹션을 다르게 보여주어야 했음
- OPEN 상태일때만 처리가 되어있어, 나머지 상태일 때, 에러바운더리로 넘어가는 이슈 발생
- 이에, 상태별 로직을 추가함
- "UPCOMING" | "CLOSED" | "END" 상태 별 예외처리 추가
- UPCOMING: 자정 ~ 이벤트 오픈 전까지 ( 오픈 예정인 이벤트가 존재 할 경우 )
- CLOSED: 이벤트 기간이 끝나지 않았지만, 인원이 마감된경우
- END: 이벤트 기간이 종료된 경우
<br/>
@thgee
> feat(CLAP-153): 퀴즈 Status 별 예외처리

- packages/service/src/apis/expectation/apiGetExpectation.ts
- packages/service/src/apis/expectation/type.ts
- packages/service/src/common/components/Marquee/Marquee.css.ts
- packages/service/src/common/components/Marquee/Marquee.tsx
- packages/service/src/components/main/Expectation/Expectations.tsx
- packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-155?atlOrigin=eyJpIjoiYjFiMThmZTdjOTFjNGFlZWJkMTBjNDk3ODA0N2UyZjQiLCJwIjoiaiJ9)
<br/>
기대평 데이터를 서버에서 받아오고, 마퀴 애니메이션 수정
- 기대평 데이터를 서버에서 받아와서 적용
- 마퀴 애니메이션 수정: 시작 시 화면에 바로 보이기 및 끊김현상 개선 
<br/>
@thgee
> feat(CLAP-155): 메인페이지 기대평 API 구현

- packages/service/src/components/main/Expectation/Expectations.tsx
- packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
- packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
- 리워드 이미지의 비율 수정
- 기대평의 쿼리키가 중복되어있던 이슈 해결
- 퀴즈에서 오픈된 퀴즈가 있음에도, 오픈예정 퀴즈가 노출되던 이슈 해결
<br/>
@thgee
> hotfix: 리워드 이미지 비율 수정, 기대평 쿼리키 중복 수정, 대체 퀴즈 노출 수정

- packages/service/src/components/partsCollection/CustomCard/CustomCard.css.ts
- packages/service/src/components/partsCollection/PartsTab/PartsCard/PartsCard.css.ts
- packages/service/src/components/partsCollection/PartsTab/PartsTab.css.ts
- packages/service/src/pages/PartsCollection/PartsCollection.css.ts
- packages/service/src/pages/PartsCollection/PartsCollection.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-157?atlOrigin=eyJpIjoiYmZjY2IwNjBlZTcwNDM4NDg3ZDkzZjk5MjExOTJjYjYiLCJwIjoiaiJ9)
<br/>
파츠 컬렉션 페이지에서 UX/UI 쪽으로 피드백이 들어와 반영
- 레이아웃 변경
<br/>
- @thgee
> feat(CLAP-157): 파츠페이지 레이아웃 수정

- packages/admin/src/App.tsx
- packages/admin/src/apis/auth/apiGetAdminAuth.ts
- packages/admin/src/common/components/GlobalNavigationBar/GlobalNavigationBar.tsx
- packages/admin/src/pages/Error/Error.css.ts
- packages/admin/src/pages/Error/Error.tsx
- packages/admin/src/pages/Error/index.ts
- packages/admin/src/router.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-153?atlOrigin=eyJpIjoiZDVjNjdhMGRkYzBhNDY4YmIzYzI3MTdhMTcwMTgzOWMiLCJwIjoiaiJ9)
<br/>
어드민 페이지에 접근 할 경우, 권한 체크를 우선적으로 하고 권한이 없을경우
발생하는 에러를 에러바운더리에서 처리하도록 함
어드민 권한이 없는 유저에게 어드민 페이지가 노출되는 이슈
- 에러바운더리 구성
- 어드민 권한을 체크하는 API 구현
- 어드민 권한이 없다는 에러 캐치 후 로그인을 유도하는 페이지로 이동
<br/>
@thgee
> feat(CLAP-153): 어드민 로그인 처리 추가

- packages/service/package.json
- packages/service/src/components/main/Banner/Banner.tsx
- packages/service/src/pages/Main/Main.tsx
- pnpm-lock.yaml
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-149)
<br/>
- `이벤트바로가기` 버튼 클릭 시 이벤트 카드로 스크롤이 이동합니다.
https://github.com/user-attachments/assets/9a2624cb-b0ae-489a-aa42-0d561a13b5bf
<br/>
- @DaeWon9
> feat(CLAP-149): 메인페이지 이벤트바로가기 버튼 클릭 시 스크롤 이동

- packages/service/src/App.tsx
- packages/service/src/common/components/ScrollToTop/ScrollToTop.tsx
- packages/service/src/common/components/ScrollToTop/index.ts
- packages/service/src/index.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-150)
<br/>
- 페이지 이동 시 스크롤이 상단으로 이동하지 않아 UX가 좋지 않았던 점 개선
https://github.com/user-attachments/assets/5715ac61-8051-4e1e-945f-80c1a8d9b5ae
<br/>
- @DaeWon9
> feat: 페이지 이동 시 스크롤 상단 고정

- packages/service/src/apis/orderEvent/apiPostOrderEventApply.ts
- packages/service/src/common/components/Button/Button.css.ts
- packages/service/src/common/components/CheckBox/CheckBox.css.ts
- packages/service/src/common/components/ModalContainer/content/modalContent.tsx
- packages/service/src/common/utils/regex.ts
- packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
- packages/service/src/pages/NQuizEventWinnerApply/NQuizEventWinnerApply.css.ts
- packages/service/src/pages/NQuizEventWinnerApply/NQuizEventWinnerApply.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-158?atlOrigin=eyJpIjoiYjRhYTRlYWI3NjFjNDFlZWI3ZGUxYzBkOGYzMzgxMWMiLCJwIjoiaiJ9)
<br/>
선착순 퀴즈 당첨자 입력 폼 수정
- 전화번호 입력이 올바르게 되었는지 사용자가 인지하기 힘든 이슈
- 올바른 번호가 입력되고, 체크박스가 체크되지 않아도 버튼이 눌리는 이슈
- 중복 제출의 경우 아무런 안내가 나오지 않던 이슈
- 전화번호 정규식을 추가하여, 입력폼의 보더의 색상에 따라 올바르게 입력되었는지 사용자가 알기 쉽게 조정함
- 올바른 번호 입력 및 체크박스 체크 전까지는 버튼을 disable상태로 변경
- 중복 제출의 경우 알림 모달을 통해 유저에게 알려주는 기능 추가
https://github.com/user-attachments/assets/7cbff242-ae94-4a59-b688-0471398ac283
<br/>
@thgee
> feat(CLAP-158): 선착순 퀴즈 당첨자 입력폼 수정

- packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
- packages/service/src/pages/PartsPick/PartsPick.css.ts
- packages/service/src/pages/PartsPick/PartsPick.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-160?atlOrigin=eyJpIjoiNzQyOTYxMjllNjBhNDA0YWI2NjdkOWM2ZDY1ZjM0NzMiLCJwIjoiaiJ9)
<br/>
파츠카드를 뽑을 시 하단부에 이름이 노출되도록 함
- 파츠카드 하단부에 이름이 노출되지 않았던 이슈
<br/>
@thgee
> feat(CLAP-160): 파츠뽑기 카드 하단에 이름 노출

- packages/service/src/components/main/Banner/Banner.tsx
- packages/service/src/components/main/EventCard/EventCard.css.ts
- packages/service/src/components/main/EventCard/EventCard.tsx
- packages/service/src/components/main/EventPeriod/EventPeriod.css.ts
- packages/service/src/components/main/EventPeriod/Timer/Timer.css.ts
- packages/service/src/components/newCar/NewCarInfo/NewCarInfo.css.ts
- packages/service/src/components/newCar/TracingCar/TracingCar.css.ts
- packages/service/src/components/pickEvent/CardCarousel/CardCarousel.tsx
- packages/service/src/components/pickEvent/JoinInfo/JoinInfo.css.ts
- packages/service/src/components/pickEvent/PrizeContainer/PrizeContainer.css.ts
- packages/service/src/components/pickEvent/PrizeContainer/PrizeContainer.tsx
- packages/service/src/components/pickEvent/PrizeContainer/PrizeItem/PrizeItem.css.ts
- packages/service/src/components/pickEvent/PrizeContainer/PrizeItem/PrizeItem.tsx
- packages/service/src/constants/breakpoints.ts
- packages/service/src/pages/Main/Main.css.ts
- packages/service/src/pages/PickEvent/PickEvent.css.ts
- packages/service/src/pages/PickEvent/PickEvent.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-159)
<br/>
- 컴포넌트 크기가 너무 커서 한눈에 잘 안 들어오는 이슈가 있었습니다.
- 전체적인 컴포넌트 크기 축소, 레이아웃 변경
- `파츠뽑기` 버튼이 화면에서 벗어나는 경우 화면 하단에 고정
<br/>
- @DaeWon9
> chore(CLAP-159): 컴포넌트 크기 축소

- packages/service/src/components/ClickInduceIcon/ClickInduceIcon.tsx
- packages/service/src/components/ClickInduceIcon/index.ts
- packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
- packages/service/src/pages/PartsPick/PartsPick.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-163)
<br/>
- 파츠뽑기 카드를 클릭하지 못하고 헤매는 유저에 대한 UX 개선
- 파츠뽑기 카드를 클릭하도록 유도하는 아이콘 구현
https://github.com/user-attachments/assets/786748b4-c88c-4326-9f9d-cc4ded5b9c49
<br/>
- @DaeWon9
> feat(CLAP-163): 파츠뽑기 클릭 유도 UI 구현

- packages/service/src/components/partsCollection/CustomCard/CustomCard.css.ts
- packages/service/src/components/partsCollection/CustomCard/CustomCard.tsx
- packages/service/src/components/partsCollection/PinContainer/Pin/Pin.css.ts
- packages/service/src/components/partsCollection/PinContainer/Pin/Pin.tsx
- packages/service/src/components/partsCollection/PinContainer/Pin/WaveCircle/WaveCircle.css.ts
- packages/service/src/components/partsCollection/PinContainer/Pin/WaveCircle/WaveCircle.tsx
- packages/service/src/components/partsCollection/PinContainer/Pin/WaveCircle/index.ts
- packages/service/src/components/partsCollection/PinContainer/Pin/index.ts
- packages/service/src/components/partsCollection/PinContainer/PinContainer.css.ts
- packages/service/src/components/partsCollection/PinContainer/PinContainer.tsx
- packages/service/src/components/partsCollection/PinContainer/index.ts
- packages/service/src/pages/PartsCollection/PartsCollection.css.ts
- packages/service/src/pages/PartsCollection/PartsCollection.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-164?atlOrigin=eyJpIjoiOTJkYjQ0ZGI0YTNmNGFkM2EzNGM4MjkxYTRhYTI5YjYiLCJwIjoiaiJ9)
<br/>
사용자가 장착한 파츠정보를, 커스텀카드 호버 시 노출되도록 기능을 추가함.
- 커스텀카드 호버시, 장착중인 파츠 정보를 핀으로 노출
- 클릭시, 설명 모달창 오픈
- 모바일뷰 구성
<br/>
https://github.com/user-attachments/assets/1d45b2ef-4db4-4d5d-afea-b8cbce5b3661
@thgee
> feat(CLAP-164): 파츠 컬렉션 커스텀카드 호버 시 파츠정보 노출

- packages/service/src/apis/expectation/apiGetCheckExpectation.ts
- packages/service/src/apis/expectation/type.ts
- packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.tsx
- packages/service/src/pages/PartsPick/PartsPick.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-161)
<br/>
- 기대평을 `응모여부 -> 기대평 작성여부` 기준으로 작성할 수 있게 변경함
- 응모완료 페이지 레이아웃 수정
<br/>
- @DaeWon9
> feat(CLAP-161): 기대평 나중에 쓸 수 있도록 수정

- packages/service/src/common/components/ModalContainer/content/modalContent.tsx
- packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
- packages/service/src/pages/PartsPick/PartsPick.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-166?atlOrigin=eyJpIjoiZTYzYTM2Mjg4NGNmNDAzN2FhMmUyMTU3MGQ1Y2MzZmEiLCJwIjoiaiJ9)
<br/>
카드뽑기 이벤트 로직 수정
- 남은 횟수가 없는 경우에도 뽑기이벤트가 진행되던 이슈
- 남은 횟수가 0일때, 뽑기 페이지로 들어온 후 카드 클릭 시 -> 안내 모달 출력
- 뽑기 진행도중 남은 횟수가 0이 될 경우 -> 해당 페이지를 유지하며 안내모달 출력
<br/>
@thgee
> fix(CLAP-166): 카드뽑기 횟수가 없는 경우에도 뽑히는 이슈

- packages/service/src/apis/partsEvent/apiPostParts.ts
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-151)
<br/>
- 서버에 쿠키 전송 가능하도록 파츠뽑기 api에 credentials 속성 추가
<br/>
- @DaeWon9
> fix(CLAP-151): 파츠뽑기 API에 `credentials` 속성 추가

- packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.css.ts
- packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-171)
<br/>
- 기대평을 이미 제출한 유저는 기대평 입력란이 보이지 않도록 하였습니다.
<br/>
- @DaeWon9
> feat(CLAP-171): 기대평 이미 제출한 유저 기대평 입력란 숨기기

- packages/service/src/pages/PickEvent/PickEvent.css.ts
- packages/service/src/pages/PickEvent/PickEvent.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-172)
<br/>
- Footer에 `지금바로뽑기` 버튼이 겹치는 순간 버튼이 사라지도록 구현하였습니다.
https://github.com/user-attachments/assets/b41b4077-ae52-404f-8f0f-5a37e143fca7
<br/>
- @DaeWon9
> fix(CLAP-172): Footer에 `지금바로뽑기` 버튼 안 겹치게 수정

- packages/service/src/components/newCar/NewCarInfo/NewCarInfo.tsx
- packages/service/src/components/newCar/TracingCar/TracingCar.css.ts
- packages/service/src/components/newCar/TracingCar/TracingCar.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-165?atlOrigin=eyJpIjoiMmIyNTMwNDdjNWYyNGY5MGE0YzI0ZmY1ZmFkZGY0M2EiLCJwIjoiaiJ9)
<br/>
트레이싱카 경로 오류 수정
- 트레이싱카의 경로가 끊기는 이슈
- 지나가지 않은 경로도 지나갔다고 표시되는 이슈
- 모바일에서 경로가 두개가 표시되는 이슈
- 경로의 길이 기준을 변경하여 올바른 길이대로 경로가 생성되게 수정
- 계산과정에서 NaN, Infinity 예외처리 추가
<br/>
@thgee
> fix(CLAP-165): 트레이싱카 경로 오류 수정

- packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/ExpirationTimer/ExpirationTimer.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-176)
<br/>
- 로그인 만료 시 타이머 음수 되는 이슈
- 로그인 만료 시 `로그인 만료` 문구 띄우기
- 로그인 연장 클릭 시 확인 모달 띄우기
<br/>
- @DaeWon9
> fix(CLAP-176): 로그인 만료 시 타이머 음수 되는 이슈 해결,  로그인 연장 클릭 시 확인 모달 띄우기

- packages/service/src/pages/Error/Error.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-177)
<br/>
- `ErrorBoundary` 에서 뒤로가기가 작동하지 않음
- 작동함
<br/>
- @DaeWon9
> fix(CLAP-177): `ErrorBoundary` 에서 뒤로가기 안 되던 이슈 해결

- packages/service/src/apis/partsEvent/apiPatchMyParts.ts
- packages/service/src/components/partsCollection/PinContainer/Pin/Pin.css.ts
- packages/service/src/components/partsCollection/PinContainer/Pin/Pin.tsx
- packages/service/src/components/partsCollection/PinContainer/PinContainer.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-181?atlOrigin=eyJpIjoiMTNjMmJjMWY5NjViNDc4Mzk2OGU4NWZiYjE3ODlmMDkiLCJwIjoiaiJ9)
<br/>
모바일뷰에서 핀컨테이너의 작동 로직 추가
- 모바일뷰에서는 호버 이벤트의 부재로 핀컨테이너의 작동이 부자연스러운 이슈
- 핀이 노출되지 않았을때도, 핀의 위치를 터치했을때, 정보를 보여주는 모달이 노출되던 이슈
- 핀의 카드이미지보다 앞에 존재하여 카드위의 핀을 터치했을떄, 핀컨테이너의 상태가 바뀌지 않는 이슈
- 모바일 뷰에서 핀컨테이너를 터치하는 이벤트를 감지하여  핀 컨테이너의 상태가 바뀌도록 추가
- 이벤트 전파를 막아 핀컨테이너를 클릭해도 내부의 핀요소까지 이벤트가 전파되는 것을 방지
- 핀의 Line, WaveCircle에 해당하는 부분에 터치이벤트를 감지하여 핀 컨테이너의 상태가 바뀌도록 추가
https://github.com/user-attachments/assets/7772d6a8-8f03-4603-b1c1-33b4b54e7ca6
<br/>
- @thgee
> feat(CLAP-181): 모바일뷰에서 핀컨테이너 터치이벤트 추가

- packages/service/src/common/components/CheckBox/CheckBox.css.ts
- packages/service/src/common/components/CheckBox/CheckBox.tsx
- packages/service/src/common/components/ClickInduceIcon/ClickInduceIcon.tsx
- packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/ExpirationTimer/ExpirationTimer.css.ts
- packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/ExpirationTimer/ExpirationTimer.tsx
- packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.css.ts
- packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
- packages/service/src/components/main/Banner/Banner.css.ts
- packages/service/src/components/main/EventPeriod/EventPeriod.css.ts
- packages/service/src/components/main/EventPeriod/EventPeriod.tsx
- packages/service/src/components/pickEvent/CardCarousel/CardCarousel.css.ts
- packages/service/src/components/pickEvent/CardCarousel/CardCarousel.tsx
- packages/service/src/pages/Main/Main.tsx
- packages/service/src/pages/NewCar/NewCar.css.ts
- packages/service/src/pages/NewCar/NewCar.tsx
- `GNB`에 현재 페이지에 따라 밑줄표시
- 로그인 타이머 `width` 고정 
- 로그인 연장시 뜨던 모달 삭제
- 메인배너 화면에 꽉 차도록 수정
- 배너이미지 아래에 스크롤 유도 아이콘 렌더링
<br/>
- @DaeWon9
> hotfix: GNB 스타일링, 이미지 크기조절, 각종 UX 개선

- packages/service/src/common/utils/formatter.ts
- packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.tsx
- packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-183?atlOrigin=eyJpIjoiZDgzMGZjNGMzOWFlNGVlNmI2ZjM0Y2VmNzkyNTFiYzYiLCJwIjoiaiJ9)
<br/>
서버에서 받아온 선착순이벤트 정보를 바탕으로
선착순이벤트의 전체 기간을 노출하도록 함.
- 노출되는 선착순 이슈의 전체 기간이 실제 기간과 맞지 않는 이슈
- 서버에서 받아온 데이터를 바탕으로 날짜를 파싱하여 노출되도록 수정
<br/>
- @thgee
> fix(CLAP-183): 선착순 이벤트 기간 노출 이슈

- packages/core/src/contexts/ModalContext.ts
- packages/core/src/hooks/useModal.ts
- packages/core/src/providers/ModalProvider.tsx
- packages/service/src/common/components/ModalContainer/ModalContainer.tsx
- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-184?atlOrigin=eyJpIjoiYzg1NGQwNjI3MGJjNGJkN2EwYmVjZWZmMTUyNmU4MWMiLCJwIjoiaiJ9)
<br/>
ModalContext, ModalProvider 타입 지정 리팩토링
- ModalContext에서 사용하던 ModalState내부 인자의 any 사용 이슈
```
import { createContext, Dispatch, SetStateAction } from "react";
export interface ModalState {
type: any;
props?: any;
}
export const ModalStateContext = createContext<ModalState | null>(null);
export const ModalSetterContext = createContext<Dispatch<
SetStateAction<ModalState>
> | null>(null);
```
- any를 제거하고 제네릭을 사용하여 타입 안전성을 높이고 코드의 품질을 개선함.
```
import { createContext, Dispatch, SetStateAction } from "react";
export interface ModalState<T, P> {
type: T;
props?: P;
}
export const ModalStateContext = createContext<ModalState<
unknown,
unknown
> | …
```
> refactor(CLAP-184): ModalContainer 리팩토링

- packages/service/index.html
- 기존 og태그의 타이틀을 보았을 떄, 이벤트 페이지의 느낌이 약하다는 의견
- 타이틀 수정: 현대자동차 - 아반떼 N 2024 | 고성능 컴팩트 스포츠카 -> 현대자동차 - 아반떼 N 2024 출시 이벤트
<br/>
- @thgee
> chore: og:title 변경

- packages/service/src/components/main/Banner/Banner.css.ts
- packages/service/src/pages/NewCar/NewCar.css.ts
- 아이폰에서 배너이미지가 화면에 가득 차는 이슈가 발생
- `height : fit-content` -> `height : auto` 로 수정
<br/>
- @DaeWon9
> hotfix: 아이폰에서 배너이미지가 화면에 꽉 차는 이슈

- packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.css.ts
- GNB에서 현재 페이지 표시의 `breakpoint` `GNB_BREAKPOINT` 가  아닌, `MOBILE_BREAKPOINT` 로 설정되어있던 이슈
- `breakpoint`를 `GNB_BREAKPOINT`로 변경
<br/>
- @DaeWon9
> __hotfix: GNB의 `active된 link`의 스타일링에 breakPoint 수정
